version: "3.9"

services:
  eventstore.db:
    image: eventstore/eventstore:21.10.0-buster-slim
    restart: always
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

 # Prometheus container to query backend metrics
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "3570:9090"
    volumes:
      - ./monitoring:/etc/prometheus/

  # Grafana container to visualize data
  grafana:
    image: grafana/grafana:5.1.0
    restart: always
    ports:
      - 3000:3000
    #user: "104"
    user: "0"
    environment:
      #- GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SECURITY_ADMIN_PASSWORD=s@ltsecretmetrics
    volumes:
      - ./monitoring/grafana:/var/lib/grafana

  nginx-logs:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter
    restart: always
    ports:
      - 127.0.0.1:4040:4040
    volumes:
      - ./nginx/logs:/mnt/nginxlogs
      - ./monitoring/prometheus-nginxlog-exporter.hcl:/etc/prometheus-nginxlog-exporter.hcl
    command: ["-config-file", "/etc/prometheus-nginxlog-exporter.hcl"]

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=salt
      - POSTGRES_DB=salt

  backend:
    image: salt-server:0.0.1-preview
    restart: always
    environment:
      - EVENTSTORE_DB_HOST=esdb://eventstore.db:2113?tls=false
      - POSTGRES_HOST=postgres:5432/salt
    depends_on:
      - eventstore.db
      - postgres

  nginx:
     build:
       context: ./nginx
       dockerfile: Dockerfile
     restart: always
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./certbot/conf:/etc/letsencrypt
       - ./certbot/www:/var/www/certbot
       - ./nginx/logs:/var/log/nginx
     depends_on:
       - backend

  certbot:
     image: certbot/certbot
     restart: unless-stopped
     volumes:
       - ./certbot/conf:/etc/letsencrypt
       - ./certbot/www:/var/www/certbot
       - ./certbot/nging_reload.sh:/nginx_reload.sh
     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; /nginx_reload.sh; sleep 12h & wait $${!}; done;'"

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
